name: WordPress Deploy Action
description:
  Deploy your WordPress plugin to the WordPress.org Plugin Repository.
author: Kadir Gün

branding:
  icon: 'heart'
  color: 'red'

inputs:
  slug:
    description: Plugin slug (e.g. my-awesome-plugin)
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
