name: Test Deploy Action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test action
        uses: kadirgun/wordpress-deploy-action@main
        with:
          slug: akismet
          dry-run: true
          svn-username: test
          svn-password: test
          build-dir: wordpress/build
          assets-dir: wordpress/.wordpress.org
