name: Test Deploy Action

on:
  workflow_dispatch:

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test action
        uses: kadirgun/wordpress-deploy-action@main
        with:
          slug: test-plugin
          dry-run: true
          svn-username: test
          svn-password: test
