name: Test Deploy Action

on:
  workflow_dispatch:
    inputs:
      mode:
        description: Deploy mode
        required: true
        default: all
        type: choice
        options:
          - all
          - assets
          - plugin
          - readme

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test action
        uses: kadirgun/wordpress-deploy-action@main
        with:
          mode: ${{ github.event.inputs.mode }}
          slug: akismet
          dry-run: true
          svn-username: test
          svn-password: test
          build-dir: wordpress/build
          assets-dir: wordpress/.wordpress.org
